version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service:
      container_name: angularcontainer  # Container name
      image: mahabara/frontend
      ports: 
        - '4200:4200' # Port mapping
      volumes: # Volume binding
        - './black-dashboard-angular /src/app'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
